spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/Ecommerce
spring.datasource.username=root
spring.datasource.password=Abhi@3146
server.port=8081
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret_key=myjwtsecretkey
server.servlet.context-path=/api/v1.0